# Generated by Django 2.1.3 on 2018-11-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educMethodPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('eventName', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=64)),
                ('plan', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='indPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planID', models.IntegerField()),
                ('year', models.CharField(max_length=64)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('changeDate', models.DateField(auto_now=True)),
                ('approval', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='litPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('pubType', models.CharField(max_length=256)),
                ('disc', models.CharField(max_length=256)),
                ('direction', models.CharField(max_length=256)),
                ('amount', models.FloatField()),
                ('edition', models.FloatField()),
                ('plan', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='otherPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('workName', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=64)),
                ('plan', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='plansFall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=256)),
                ('workType', models.CharField(max_length=64)),
                ('september', models.FloatField()),
                ('october', models.FloatField()),
                ('november', models.FloatField()),
                ('december', models.FloatField()),
                ('januar', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='plansFallHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=256)),
                ('workType', models.CharField(max_length=64)),
                ('september', models.FloatField()),
                ('october', models.FloatField()),
                ('november', models.FloatField()),
                ('december', models.FloatField()),
                ('januar', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='plansSpring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=256)),
                ('workType', models.CharField(max_length=64)),
                ('february', models.FloatField()),
                ('march', models.FloatField()),
                ('april', models.FloatField()),
                ('may', models.FloatField()),
                ('june', models.FloatField()),
                ('july', models.FloatField()),
                ('august', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='plansSpringHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=256)),
                ('workType', models.CharField(max_length=64)),
                ('february', models.FloatField()),
                ('march', models.FloatField()),
                ('april', models.FloatField()),
                ('may', models.FloatField()),
                ('june', models.FloatField()),
                ('july', models.FloatField()),
                ('august', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='sciPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('eventName', models.CharField(max_length=256)),
                ('as_a', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=64)),
                ('plan', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('post', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='trainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_p', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=64)),
                ('trainingType', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('plan', models.FloatField()),
                ('fact', models.FloatField()),
                ('usern', models.CharField(default='usr', max_length=64)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan')),
            ],
        ),
        migrations.AddField(
            model_name='indplan',
            name='teacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.teacher'),
        ),
        migrations.AddField(
            model_name='educmethodplan',
            name='planID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_tables.indPlan'),
        ),
    ]
